
CREATE TABLE q2(
   QuesID INT,
   QuesText VARCHAR(300),
   NumberOfHint INT
);
DROP VIEW IF EXISTS TFQues CASCADE;
DROP VIEW IF EXISTS MCQuesID  CASCADE;

DROP VIEW IF EXISTS MCHINTID  CASCADE;
DROP VIEW IF EXISTS MCNOHINTID  CASCADE;

DROP VIEW IF EXISTS  MCHINTCount CASCADE;
DROP VIEW IF EXISTS  MCNULL CASCADE;

DROP VIEW IF EXISTS  MCFinal CASCADE;
DROP VIEW IF EXISTS  MCFinal2 CASCADE;

DROP VIEW IF EXISTS  NUMID CASCADE;
DROP VIEW IF EXISTS NUMQues1  CASCADE;
DROP VIEW IF EXISTS NUMQues2  CASCADE;
DROP VIEW IF EXISTS NUMNULL  CASCADE;
DROP VIEW IF EXISTS NUMNULL1  CASCADE;

DROP VIEW IF EXISTS NUMFinal  CASCADE;
DROP VIEW IF EXISTS NUMFinal2  CASCADE;
DROP VIEW IF EXISTS FINAL  CASCADE;





--define the number of hint AS null to the TF Question
CREATE VIEW TFQues AS
SELECT QuesID, QuesText, NULL AS NumberOfHint
FROM QuestionBank
WHERE QuestionBank.TYPE = 'TF';


--count the number of hint from each of the MC Question

CREATE VIEW MCQuesID AS
SELECT QuesID 
FROM MCQuesFalse;

CREATE VIEW MCHINTID AS
SELECT QuesID
FROM MCHINT
GROUP BY QuesID;

CREATE VIEW MCNOHINTID AS
(SELECT * FROM MCQuesID) EXCEPT (SELECT * FROM MCHINTID);

--deal with MC question with hint
CREATE VIEW MCHINTCount AS
SELECT MCHINTID.QuesID, count(HINT) AS NumberOfHint
FROM MCHINTID, MCHINT
WHERE MCHINTID.QuesID = MCHINT.QuesID
GROUP BY MCHINTID.QuesID;


-- deal MC Question with no hint
CREATE VIEW MCNULL AS
SELECT MCNOHINTID.QuesID, 0 AS NumberOfHint
FROM MCNOHINTID;

-- join them together
CREATE VIEW MCFinal AS
(SELECT * FROM MCHINTCount) UNION (SELECT * FROM MCNULL);

CREATE VIEW MCFinal2 AS
SELECT MCFinal.QuesID, QuesText, MCFinal.NumberOfHint
FROM MCFinal, QuestionBank
--GROUP BY MCFinal.QuesID, MCFinal.NumberOfHint
WHERE MCFinal.QuesID = QuestionBank.QuesID;

-- DEAL with the Number Question
CREATE VIEW NUMID AS
SELECT QuesID 
FROM NumQuesFalse;

CREATE VIEW NUMQues1 AS
SELECT NumQuesFalse.QuesID AS QuesID, HINT AS HINT
FROM NumQuesFalse
WHERE HINT IS NOT NULL;

CREATE VIEW NUMQues2 AS
SELECT NUMQues1.QuesID AS QuesID, count(HINT) AS NumberOfHint
FROM NUMQues1
GROUP BY QuesID;


-- deal with no hint
CREATE VIEW NUMNULL AS
(SELECT * FROM NUMID) EXCEPT (SELECT QuesID FROM NUMQues2);

CREATE VIEW NUMNULL1 AS
SELECT QuesID, 0 AS NumberOfHint
FROM NUMNULL;


-- join them together
CREATE VIEW NUMFinal AS
(SELECT * FROM NUMNULL1) UNION (SELECT * FROM NUMQues2);

CREATE VIEW NUMFinal2 AS
SELECT NUMFinal.QuesID, QuesText, NumberOfHint
FROM NUMFinal, QuestionBank
WHERE NUMFinal.QuesID = QuestionBank.QuesID;

CREATE VIEW FINAL AS
(SELECT * FROM TFQues) UNION (SELECT * FROM MCFinal2) UNION (SELECT * FROM NUMFinal2);

--INSERT INTO q2()

INSERT INTO q2(QuesID, QuesText, NumberOfHint)
              (SELECT QuesID AS QuesID,
                      QuesText AS QuesText,
                      NumberOfHint AS NumberOfHint
               FROM Final
              );

